---
- name: 2T Scheduler Update
  hosts: localhost
  tasks:
  - name: Get date and time
      shell: date --date 'now + "{{minuets}}" "{{min_hour}}"' '+%Y%m%dT%H:%M:%SZ'
      register: date_time
    - name: Update Stage DCs
      ansible.controller.schedule:
        controller_host: "{{controller_host}}"
        controller_username: "{{controller_username}}"
        controller_password: "{{controller_password}}"
        validate_certs: false
        name: "{{ controller_username }}"
        state: present
        unified_job_template: "{{execute_template}}"
        extra_data:
          schedule_name: "{{schedule_name}}"
        rrule: "DTSTART:{{date_time.stdout}} FREQ=MONTHLY;INTERVAL=1;BYDAY=2TU"
      register: result
