---
- name: Disable a Veeam Backup Job
  hosts: all
  gather_facts: true
  tasks:
    - name: Disable the Tier Veeam job via PowerShell
      ansible.windows.win_powershell:
        script: |

          # Define the job name
          $jobName = "{{ Tier* }}"

          # Get the job object
          $job = Get-VBRJob -Name $jobName

          if ($job) {
            # Disable the job
            Disable-VBRJob -Job $job -Confirm:$false
            Write-Host "Veeam job '$jobName' has been disabled."
          } else {
            Write-Host "Veeam job '$jobName' not found."
          }
      register: veeam_disable_output

    - name: Display the result
      ansible.builtin.debug:

    - name: Disable the iLand Veeam job via PowerShell
      ansible.windows.win_powershell:
        script: |

          # Define the job name
          $jobName = "{{ iLand* }}"

          # Get the job object
          $job = Get-VBRJob -Name $jobName

          if ($job) {
            # Disable the job
            Disable-VBRJob -Job $job -Confirm:$false
            Write-Host "Veeam job '$jobName' has been disabled."
          } else {
            Write-Host "Veeam job '$jobName' not found."
          }
      register: veeam_disable_output

    - name: Display the result
      ansible.builtin.debug:
