- name: Disable Veeam Job
  hosts: your_veeam_server_group # Defined in your inventory
  gather_facts: false
  tasks:
    - name: Load Veeam PowerShell Snap-in & Disable Job
      win_shell: |
        Add-PSSnapin VeeamPSSnapin -ErrorAction Stop;
        Get-VBRJob -Name "Tier*" | Disable-VBRJob -ErrorAction Stop;
        Write-Host "Job 'Tier*' disabled successfully.";
      args:
        executable: powershell.exe
      register: disable_job_result
      changed_when: disable_job_result.rc == 0
