---
- name:  #Enter a name for playbook
  hosts: all
  gather_facts: true
  tasks:
    - name: Disable the iLand Veeam job via PowerShell
      ansible.windows.win_powershell:
        script: |
          $jobName = "{{ iLand* }}" | $job = Get-VBRJob -Name $jobName | if ($job) { | Disable-VBRJob -Job $job -Confirm:$false | Write-Host "Veeam job '$jobName' has been disabled." | } else { | Write-Host "Veeam job '$jobName' not found." | }
      register: veeam_disable_output
    - name: Display the result
      ansible.builtin.debug:
...
