---
- name: Run inline PowerShell script
  hosts: windows_hosts
  gather_facts: false
  tasks:
    - name: Execute multi-lined PowerShell commands
      ansible.windows.win_shell: "{{ lookup('file', 'scripts/veeam_disable.ps1') }}
      register: pwsh_output

    - name: Display script output
      ansible.builtin.debug:
        var: pwsh_output.stdout_lines
