---
- name: Manage Windows Services
  hosts: all
  gather_facts: true

  tasks:
    - name: Check service status and start if stopped
      win_service:
        name: "{{ item.name }}"
        state: started
      loop:
        - { name: "MSExchangeADTopology" } # Replace with your service names
        - { name: "MSExchangePop3" }
        - { name: "MSExchangeImap4" }
        - { name: "MSExchangeServiceHost" }
        - { name: "MSExchangeTransport" }
      register: service_status

    - name: Display service status changes
      debug:
        msg: "Service '{{ item.item.name }}' was {{ 'started' if item.changed else 'already running' }}"
      loop: "{{ service_status.results }}"
      when: item.changed or item.skipped
