---
- name: Manage Windows Service
  hosts: all # Replace with the name of your Windows host group in AWX
  gather_facts: false
  tasks:
    - name: Check and restart service if stopped
      ansible.windows.win_service:
        name: YourServiceName # Replace with the actual service name (e.g., 'Spooler')
        state: started
        start_mode: auto # Optional: Set the startup mode to automatic if needed
      register: service_status

    - name: Display service status
      ansible.builtin.debug:
        msg: "Service '{{ service_status.name }}' is now in state: {{ service_status.state }}"
