---
- name: LT Scheduler
  hosts: localhost
  tasks:
    - name: Build a schedule for Demo Job Template
      ansible.controller.schedule:
        controller_host: "{{controller_host}}"
        controller_username: "{{controller_username}}"
        controller_password: "{{controller_password}}"
        validate_certs: false
        name: "{{ controller_username }}"
        state: present
        unified_job_template: "{{template_name}}"
        extra_data:
          schedule_name: "{{schedule_name}}"
        rrule: "FREQ=MONTHLY;INTERVAL=1;BYDAY=-1TU"
      register: result
