- name: Windows Reboot Playbook
  hosts: all
  gather_facts: true
  vars:
    reboot_timeout: 3600
    post_reboot_delay: 120
    test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
  tasks:
    - name: Reboot the machine and validate Netlogon service
      win_reboot:
        reboot_timeout: "{{ reboot_timeout }}"
        post_reboot_delay: "{{ post_reboot_delay }}"
        test_command: "{{ test_command }}"

