- name: Windows Updates Playbook
  hosts: all
  gather_facts: true
  vars:
    update_categories:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot_after_updates: false
    reboot_timeout: 3600
    log_path: C:\ansible_wu.txt
  tasks:
    - name: Install specified Windows updates
      ansible.windows.win_updates:
        category_names: "{{ update_categories }}"
        reboot: "{{ reboot_after_updates }}"
        reboot_timeout: "{{ reboot_timeout }}"
        log_path: "{{ log_path }}"
        state: installed

- name: Windows Reboot Playbook
  hosts: all
  gather_facts: true
  vars:
    reboot_timeout: 3600
    post_reboot_delay: 120
    test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
  tasks:
    - name: Reboot the machine and validate Netlogon service
      win_reboot:
        reboot_timeout: "{{ reboot_timeout }}"
        post_reboot_delay: "{{ post_reboot_delay }}"
        test_command: "{{ test_command }}"
